name: wrangling
channels:
  - defaults
dependencies:
  - pip=20.*
  - python=3.8.*
  - ipykernel
  - jupyter
  - pip:
      - numpy
      - pandas
      - scikit-learn
      - tensorflow
      - matplotlib
      - seaborn
      - jupyter
      - scipy
      - xgboost


